### ISSUE TITLE
Its not clear where the parsed info is

### ISSUE THREAD

**Issue by budarin** [rvboris/koa-useragent#11]
Please provide minimal sample how to get parsed info.
Where I should to look for the info?

**Comment by rvboris** [comment]
Hello, example provided in README, also you can look the [test file](https://github.com/rvboris/koa-useragent/blob/master/test/koa.js).

**Comment by budarin** [comment]
Example in readme doesn show where parsed fata is - app. Context or request object0:28, 26 марта 2017 г., Boris Ryabov <notifications@github.com>:Hello, example provided in README, also you can look the test file.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




С уважением Бударин Вадим

**Comment by rvboris** [comment]
I update lib to support koa2, you can try it, also i fix readme. Everything is very simple there, so I do not see the point of doing a full code sample.

**Comment by budarin** [comment]
thanks!
