### ISSUE TITLE
Chrome on Android 8.0 misdetected as Opera without version

### ISSUE THREAD

**Issue by stefanb2** [rvboris/koa-useragent#13]
UserAgent string from Chrome 64 on Android 8.0 on a OnePlus phone. Also reproduced with a Nokia 6 running 8.0.
```javascript
$ node
> const ua = require('koa-useragent/lib/useragent');
undefined
> let a = new ua('Mozilla/5.0 (Linux; Android 8.0.0; ONEPLUS A3003 Build/OPR6.170623.013) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36');
undefined
> a
{ isAuthoritative: true,
  isMobile: true,
...
  isAndroid: true,
...
  isOpera: true,
...
  silkAccelerated: false,
  browser: 'Opera',
  version: undefined,
  os: 'Linux',
  platform: 'Android',
  geoIp: {},
  source: 'Mozilla/5.0 ...' }
```
The problem is the ` Build/OPR...` part which matches the Opera regex. The problematic string disappears when switching to desktop mode.

Seems to be a common problem everywhere. Similar to these other github issues:

* https://github.com/lancedikson/bowser/issues/199
* https://github.com/extnet/Ext.NET/issues/1563
* http://useragentapi.com/ mis-detects the browser too

**Comment by rvboris** [comment]
Thank you!

**Comment by stefanb2** [comment]
Thanks for the quick release!
