### ISSUE TITLE
[version 2.2.1 problem] middle should be function

### ISSUE THREAD

**Issue by fsiaonma** [rvboris/koa-useragent#31]
when i use 

``` js
cosnt agent = require('koa-useragnet');
```
whitch i found that return 

```js 
{ default: asyncFunction }
```
so it will throw an exception when i use `app.use(userAgent)`

---

last i set the version in `2.0.0`.

hope to fix the proble . thx.....

**Comment by rvboris** [comment]
Hello, this is due to the transition to es6 modules. You can use .default or i can release next major without default property and you can use destructuring like `const {useAgent} = require('koa-useragent');`

**Comment by rvboris** [comment]
I changed default export to named export, now you can use it as I describe in the previous comment

try version 2.1.3

**Comment by veedrin** [comment]
shit

**Comment by laeshiny** [comment]
there is typo, this is correct `const {userAgent} = require('koa-useragent')`

**Comment by rvboris** [comment]
Thank you, I fixed it.
